### ISSUE TITLE
Failing to send tracking events in server-side context

### ISSUE THREAD

**Issue by quadmachine** [analytics-debugger/ga4mp#14]
Hi, I'm trying to send a tracking event using your library, it's running in a [Nuxt](https://nuxtjs.org/) app, within SSR context, so basically Node, and `window` and other browser specific stuff is not available.
Sending fails with error:

```
 ERROR  Could not send tracking event window is not defined                                                              14:22:13

  at clientHints (node_modules/@analytics-debugger/ga4mp/dist/ga4mp.umd.js:251:5)
  at Object.trackEvent (node_modules/@analytics-debugger/ga4mp/dist/ga4mp.umd.js:603:7)
  at sendToTackingServer (modules/serverSideTracking/helper/serverSideTrackingHelper.ts:216:14)
  at _default (modules/serverSideTracking/hooks/trackSrrPageLoad.ts:134:53)
  at node_modules/hable/dist/hable.js:1:990
  at node_modules/hable/dist/hable.js:1:208
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async nuxtMiddleware (node_modules/@nuxt/server/dist/server.js:147:5)
```

This is my code:

```
const ga4mp = require('@analytics-debugger/ga4mp/dist/ga4mp.umd.js')

ga4track = ga4mp(['G-XXXXXXXXXX'], {
  user_id: undefined,
  client_id: seid,
  non_personalized_ads: true,
  debug: true,
  endpoint: process.env.SERVER_SIDE_TRACKING_COLLECTOR,
})
ga4track.setEventsParameter(
  'api_secret',
  process.env.SERVER_SIDE_TRACKING_API_KEY
)

ga4track.trackEvent('page_view')
```

Maybe I'm missing some configuration option, or perhaps it's a bug? Not sure, any help is appreciated.

**Comment by thyngster** [comment]
Hi @quadmachine could you provide a simple repo to replicate this?

**Comment by quadmachine** [comment]
@thyngster I've perhaps fixed the issue, in `clientHints` function check on line 211 doesn't break if I change from
```
if (window && !('navigator' in window)) {
```
to
```
if (typeof window === 'undefined') {
```

Perhaps I can make a MR for this?

**Comment by quadmachine** [comment]
@thyngster Can confirm the fix is working, tnx!
